import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={"w-full h-full"}>
      <head>
        <title>LASA Coffeehouse</title>
      </head>
      <body className={"w-full h-full " + inter.className}>{children}</body>
    </html>
  )
}
